import "./globals.css";
import "bootstrap/dist/css/bootstrap.rtl.min.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import BootstrapClient from "@/components/libraries/BootstrapClient";
import Header from "@/components/layouts/Header";

export const metadata = {
	title: "فروشگاه غذا",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<Header />
				{children}

				<BootstrapClient />
			</body>
		</html>
	);
}
